class Assets {
  Assets._();

  static const String Logo = "assets/Logo/logo.png";
  static const String Onb1 = "assets/Onboarding/onb1.png";
  static const String Onb2 = "assets/Onboarding/onb2.png";
  static const String Onb3 = "assets/Onboarding/onb3.png";
  static const String Button = "assets/but.png";
  static const String facebbok = "assets/SM/facebook.png";
  static const String google = "assets/SM/gmail.png";
  static const String notif = "assets/notife.png";
  static const String menu = 'assets/menu.png';
  static const String grid1 = 'assets/grid1.png';
  static const String pic1 = 'assets/pic1.png';
  static const String pic2 = 'assets/pic2.png';
  static const String pic3 = 'assets/pic3.png';
  static const String location = 'assets/local.png';
  static const String card = 'assets/card.png';
  static const String org = 'assets/org.png';
  static const String user = 'assets/user.png';
  static const String edit = 'assets/edit.png';
  static const String add = 'assets/add.png';
  static const String message = 'assets/message.png';
  static const String notification = 'assets/notification.png';
  static const String invite = 'assets/invite.png';
  static const String invite1 = 'assets/invite1.png';
  static const String map = 'assets/map.png';
  static const String export = 'assets/export.png';
  static const String agenda = 'assets/agenda.png';
  static const String profile = 'assets/profil.png';
  static const String mainadd = 'assets/mainadd.png';
  static const String sport = 'assets/sport.png';
  static const String next = 'assets/next.png';
  static const String event = 'assets/event.png';
  static const String back = 'assets/back.png';
  static const String sea1 = 'assets/sea1.png';
  static const String sea2 = 'assets/sea2.png';
  static const String sea3 = 'assets/sea3.png';
  static const String sea4 = 'assets/sea4.png';
  static const String sea5 = 'assets/sea5.png';
  static const String filtre='assets/filtre.png';
}
